language: node_js
node_js: 9
cache:
  directories:
  - "/node_modules/"
branches:
  only:
  - live
  - dev
before_install:
- npm install --save-dev @alrra/travis-scripts
- $(npm bin)/set-up-ssh --key "$encrypted_bafa79c953bb_key" --iv "$encrypted_bafa79c953bb_iv" --path-encrypted-key "keys/gitkeys.enc"
- chmod +x build.sh
install:
- npm install
script:
- "./build.sh"