language: node_js
node_js: 9
cache:
  directories:
  - "/node_modules/"
branches:
  only:
  - live
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_bafa79c953bb_key -iv $encrypted_bafa79c953bb_iv -in keys/gitkeys.enc -out gitkeys -d
- chmod +x build.sh
- git status
- git checkout dev
- git status
install:
- npm install
script:
- "./build.sh"
after_success:
- eval "$(ssh-agent -s)" #start the ssh agent
- chmod 600 gitkeys # this key should have push access
- ssh-add gitkeys
- git add --all
- git commit -m "Travis deploy"
- git remote set-url origin git@github.com:LocalCoinIS/LocalCoin-ui.git
- echo $TRATRAVIS_PULL_REQUEST_BRANCH
- echo $TRAVIS_BRANCH
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BUILD_NUMBER
- git push origin dev