language: node_js
node_js: 9
cache:
  directories:
  - "/node_modules/"
branches:
  only:
  - live
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_bafa79c953bb_key -iv $encrypted_bafa79c953bb_iv -in keys/gitkeys.enc -out gitkeys -d
- chmod +x build.sh
- chmod +x deploy.sh
install:
- npm install
script:
- "./build.sh"
after_success:
- "./deploy.sh"