version: "2"
volumes:
 wallet_build: {}

services:
 web-wallet:
  build: .
  ports:
    - "8080:80"
    - "9999:8080"
  env_file:
    - .env
  volumes:
   - wallet_build:/localcoin-ui/build/dist
   - .:/localcoin-ui
